//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplomado_MVC_UASD_Estudiante_ImageUpload.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblEstudiante
    {
        public int EstudianteId { get; set; }
        [Required(ErrorMessage = "El Nombre es Obligatorio")]
        public string Nombres { get; set; }
        [Required(ErrorMessage = "El Apellido es Obligatorio")]
        public string Apellidos { get; set; }
        [Required(ErrorMessage = "La Dirección es Obligatoria")]
        public string Direccion { get; set; }
        [Required(ErrorMessage = "El Telefono Contacto es Obligatorio")]
        public string Telefono { get; set; }
        [Required(ErrorMessage = "La Cedula es Obligatoria")]
        [MinLength(11, ErrorMessage = "La Cedula Debe Tener 11 Digitos")]
        public string Cedula { get; set; }
        public string ImageUrl { get; set; }
    }
}
